[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cfis_utils"
version = "v2025.04.12.04"
authors = [
  { name="Bryan Casanelli", email="bryancasanelli@gmail.com" },
]
description = "Utility classes and methods used by our lab."
readme = "README.md"
requires-python = ">=3.8"
license = { file="LICENSE" }
dependencies = [
    "colorlog",
]

[project.urls]
Repository = "https://github.com/CFIS-UFRO/cfis-utils"

[tool.setuptools.packages.find]
where = ["src"]